#ifndef _DEFINES_H_
#define _DEFINES_H_

#define MIN_GOAL_RANGE_INCHES 100 
#define MAX_GOAL_RANGE_INCHES 102
#define CATAPULT_FORWARD_CATCH_AMOUNT 10
#define CATAPULT_BACK_OFF_AMOUNT 100
#define STOPPED_AND_LATCHED_ITERATIONS 10
#define REEDWATCH_PRIORITY 150 // 0 - 255, 0 is highest

#define RASPBERRY_PRIORITY 150 // 0 - 255, 0 is highest

//#define DEBUG_DRIVE
//#define DEBUG_PICKUP
//#define DEBUG_CATAPULT

#endif /*_DEFINES_H_*/
