#ifndef _DEFINES_H_
#define _DEFINES_H_

#define MIN_GOAL_RANGE_INCHES 100 
#define MAX_GOAL_RANGE_INCHES 102
#define STOPPED_AND_LATCHED_ITERATIONS 10

//#define DEBUG_DRIVE
//#define DEBUG_PICKUP
//#define DEBUG_CATAPULT
//#define DEBUG_KAREN

#endif /*_DEFINES_H_*/
